project_name: 'water_masked_pretrain'
log_dir: './experiments_masked/water_egnn_pretrain_noised'
gpu: 'cuda:0'

lr: 1.e-4    # if fine tune set to 4.5e-5
min_lr: 1e-7
weight_decay: 1e-4

epochs: 25
warmup_epochs: 0
patience_epochs: 0
seed: 1234
alternating_task: False

load_model: None
# Load the pretrained GNN model
# load_model: ckpt/schnet         # pre-trained SchNet
# load_model: ckpt/se3transformer # pre-trained SE(3)-Transformer
# load_model: experiments_dft/water_egnn_pretrain/checkpoints         # pre-trained EGNN
# load_model: ckpt/torchmdnet     # pre-trained TorchMD-Net

# Select the GNN model. Supported models:
# - SchNet: K. T. Schütt et al., https://aip.scitation.org/doi/10.1063/1.5019779 
# - SE(3)-Transformer: F. B. Fuchs et al., https://arxiv.org/abs/2006.10503
# - EGNN: V. G. Satorras et al., https://arxiv.org/abs/2102.09844 
# - TorchMD-Net: P. Thölke et al., https://arxiv.org/abs/2202.02541
# The defualt settings are listed below.

training:
  batch_size: 16
  num_workers: 12

model: 
  # name: "SchNet"
  # num_atoms: 28
  # bond_feat_dim: 1
  # num_targets: 1
  # hidden_channels: 128
  # num_filters: 128
  # num_interactions: 5
  # num_gaussians: 32
  # cutoff: 3.4
  # max_num_neighbors: 32
  # readout: 'add'
  # auto_grad: True
  # pretrain_return: True

  # name: 'SE3Transformer'
  # num_layers: 3
  # atom_feature_size: 28
  # num_channels: 8
  # num_degrees: 4
  # edge_dim: 4
  # div: 4
  # pooling: 'avg'
  # n_heads: 2
  # cutoff: 5.0
  # max_num_neighbors: 32

  # name: "EGNN"
  # hidden_channels: 128
  # in_edge_nf: 0
  # n_layers: 5
  # residual: True
  # attention: False
  # normalize: True
  # tanh: False
  # cutoff: 3.5
  # max_atom_type: 28
  # max_chirality_type: 5
  # max_num_neighbors: 32
  # use_pbc: True
  # pretrain_return: True
  # denoise_return: False

  name: "ForceNet"
  num_atoms: 2 # unused
  bond_feat_dim: 128 # unused
  num_targets: 1 # unused
  hidden_channels: 128
  decoder_hidden_channels: 128
  num_interactions: 5
  cutoff: 3.4
  feat: 'full'
  num_freqs: 50
  max_n: 3
  basis: 'sphallmul'
  pretrain_return: False

  # name: 'GNS'
  # particle_dimensions: 3
  # nnode_in: 131
  # nedge_in: 4
  # latent_dim: 128
  # nmessage_passing_steps: 10
  # nmlp_layers: 2
  # mlp_hidden_dim: 128
  # connectivity_radius: 3.4
  # nparticle_types: 100
  # particle_type_embedding_size: 128

  # name: "TorchMD-Net"
  # hidden_channels: 256
  # num_layers: 6
  # num_rbf: 32
  # rbf_type: "expnorm"
  # trainable_rbf: True
  # activation: "silu"
  # attn_activation: "silu"
  # neighbor_embedding: True
  # num_heads: 8
  # distance_influence: "both"
  # cutoff_lower: 0.0
  # cutoff_upper: 5.0
  # max_atom_type: 28
  # max_chirality_type: 5
  # max_num_neighbors: 32

# Select the dataset. Supported datasets:
# - ANI-1: J. S. Smith et al., https://www.nature.com/articles/sdata2017193
# - ANI-1x: J. S. Smith et al., https://www.nature.com/articles/s41597-020-0473-z
# - ISO17: K. T. Schütt et al., https://arxiv.org/abs/1706.08566
# - MD22: S. Chmiela et al., https://www.science.org/doi/10.1126/sciadv.adf0873
# - SPICE: P. Eastman et al., https://www.nature.com/articles/s41597-022-01882-6
dataset:
  # data_dir: 'RPBE-waterdataX.npz'
  # name: 'RPBE'
  # num_samples: -1
  # checkfile: False
  # masking_ratio: 0.5
  # noise_scale: 1
  # alternating_ratio: 0

  # data_dir: 'water_data_tip3p/'
  # name: 'tip3p'
  # num_samples: 1000
  # num_seeds: 10
  # m_num: 258
  # masking_ratio: 0.5
  # noise_scale: 1
  # alternating_ratio: 0
  # checkfile: False

  root: 'md17_datasets/'
  name: 'revised benzene'
  masking_ratio: 0.5
  noise_scale: 0
  pretrain: True
  num_samples: -1
  force_reload: False
  single_molecule: False
  revised: True

  # valid_size: 0.1
  # test_size: 0.1
  # data_dir: './ANI-1'
  # data_dir: './ANI-1x'
  # data_dir: './iso17'
  # data_dir: './MD22/md22_Ac-Ala3-NHMe.xyz'
  # data_dir: './MD22/md22_DHA.xyz'
  # data_dir: './MD22/md22_stachyose.xyz'
  # data_dir: './MD22/md22_AT-AT.xyz'
  # data_dir: './MD22/md22_AT-AT-CG-CG.xyz'
  # data_dir: './MD22/md22_buckyball-catcher.xyz'
  # data_dir: './MD22/md22_double-walled_nanotube.xyz'
  # data_dir: './SPICE'
  # seed: 666